### ISSUE TITLE
구체적인 주제를 결정합니다

### ISSUE THREAD

**Issue by niceaji** [CodingDolharrbang/document#1]
## 주제

생활에 도움을 주는 크롬확장 프로그램 개발

## 의견들

- 현재 위치 기반으로 날씨(추가로 다른것까지)를 보여주는 프로그램
- 각 기업들의 채용정보를 크롤링해서 한눈에 채용정보를 볼 수 있는 프로그램
-세계 각 지역의 시간 보여주기 : 특정 나라를 상단에 고정
- 메모 프로그램 : 웹 브라우저를 살펴보다 기록할 것이 생기면 확장 프로그램을 실행하여 바로 기록을 할 수 있도록 도와주는 프로그램. 기록된 메모를 sns나 메일로 전송하는 시스템 구축.
- 캘린더 프로그램 : 일정 관리를 할 수 있는 확장 프로그램, 일정을 기록하고 관리하며 한 눈에 보여주도록 한다.

한달안에 실행할수 있는 보다 구체적인 주제를 정합니다.

**Comment by khl2bb** [comment]
## 제가 생각했던 크롬 프로그램 기능
- 일정이 입력되면 현재 시간에 따른 특정 일정 알림 기능
- 사진 업로드를 통한 시간표, 일정표 배경화면 등록 기능
- ~~유튜브 썸네일을 자동으로 찾아주는 기능 (해당 영상 썸네일이 영상 어느 구간에 있는지)~~
- ~~단어 사전 검색 기능(네이버 사전 연동)~~
- ~~이메일 통합 알림 기능(구글, 네이버, 다음, 제주대웹메일 등)~~
- 제주대학교 or 관련 게시판 출력
- 수강신청 도우미()

**Comment by YeSeul-0w0** [comment]
세계 각 지역의 시간 보여주기 : 특정 나라를 상단에 고정할 수 있게 만들면 좋을 것 같습니다.

메모 프로그램 : 웹 브라우저를 살펴보다 기록할 것이 생기면 확장 프로그램을 실행하여 바로 기록을 할 수 있도록 도와주는 프로그램. 기록된 메모를 sns나 메일로 전송하는 시스템 구축.

캘린더 프로그램 : 일정 관리를 할 수 있는 확장 프로그램, 일정을 기록하고 관리하며 한 눈에 보여주도록 한다.

▶생활에 도움을 주는 확장 프로그램 위주로 생각해봤습니다.

**Comment by whe0107** [comment]
1. 헌재 위치를 기반으로 날씨 및 다른 것까지 보여주는 프로그램

2. 각 기업들의 채용 정보를 크롤링해서 한 눈에 채용 정보를 볼 수 있는 프로그램
