### ISSUE TITLE
JS 스터디

### ISSUE THREAD

**Issue by niceaji** [CodingDolharrbang/document#2]
진우님이 공유해준 링크로 스터디 잘하고 계신가요? :)

> 제가 아까 언급한 크롬 앱 만드는 강좌 주소입니다. 노마드코더 아카데미입니다.
> https://academy.nomadcoders.co/p/javascript-basics-for-absolute-beginners-kr
> 바닐라 JS 이외에 타입스크립트, React 강좌도 있습니다.

**Comment by khl2bb** [comment]
- https://academy.nomadcoders.co/p/javascript-basics-for-absolute-beginners-kr
이 course에는 크롬 개발자 대시보드를 이용하는 내용이 없더라구요.
course 이름 : 바닐라 JS로 크롬 앱 만들기

- 좀 오래된 영상이긴 한데, '생활코딩'에서 코딩 확장 프로그램 등록을 하는 course가 있었습니다.
링크 적어둡니다.
https://www.youtube.com/watch?v=uROsIBGAmgo
course 이름 : 웹페이지에서 공부한 단어의 수를 세기 (크롬 확장 기능 만들기)

**Comment by niceaji** [comment]
수고하셨습니다
