### ISSUE TITLE
시나리오를 작성합니다

### ISSUE THREAD

**Issue by niceaji** [CodingDolharrbang/document#3]
간단하게 화면구성요소와 필요한 시나리오들을 위키에 정리합니다.

**Comment by niceaji** [comment]
https://github.com/CodingDolharrbang/document/wiki/%ED%9A%8C%EC%9D%98-%EB%82%B4%EC%9A%A9-%EC%A0%95%EB%A6%AC

- 시나리오를 보면 굳이 왜 확장 프로그램으로 하지 않아도 웹서비스로만 해도 좋지 않을까요? 
- 확장프로그램보다 더 많은 사용자가 사용할수도 있고
- 왜 이런게 필요할지에 대한 이야기가 더 있으면 좋을것 같아요. 사용자가 해당서비스를 사용하면서 얻을수 있는 점

**Comment by niceaji** [comment]
화면 그림말고 좀더 구체적인 실행방법등에 대해서도 기술이 되어야 할것 같아요.

- 인재상을 가져오는 방법, 저장하는 방법
- 랜덤으로 뿌려주나?
- 지원하기의 링크는?

**Comment by YeSeul-0w0** [comment]
- 기본적으로 확장 프로그램을 하기로 했기에 확장 프로그램을 생각하고 있었습니다.
→ 만약에 웹페이지로 구현을 하게 된다면 IP주소로 접근하는 방식을 택해야할까요? 
- 자기소개서를 쓸 때 기업의 인재상을 하나하나 찾아보는 번거로움을 덜어낼 수 있습니다.
<br>
<hr>
<br>
<ul>
<li>인재상을 이미지 파일로 정리하여 배너로 넘길 예정입니다. <Br>
→ 이 부분에서 기업의 수가 늘어나면 배너로 넘어가는 기업이 많아 조금 불편한 점이 생길 수 있을 것 같습니다.</li>
<li>랜덤보다는 기업을 가나다라 순서대로 배치하여 인재상을 보여주는 게 좋을 것 같습니다.</li>
<li>지원하기 링크는 버튼으로 구현하면 좋을 것 같습니다.</li>
</ul>

**Comment by niceaji** [comment]
@Choi33 
- github에서 html호스팅 가능합니다 https://opentutorials.org/course/3084/18891
- 이미지로 할경우 DB화가 어려울것 같아요.  텍스트로 하는게 좋아보아요  json

**Comment by YeSeul-0w0** [comment]
오늘 만나서 간단하게 회의했습니다.

- 인재상이 없는 기업들이 있어 해당 주제를 계속 유지하기 어렵다고 판단되어 주제를 바꾸게 되었습니다.
- 시간과 날씨, to-do list가 있는 생활 밀착형 크롬 확장 앱을 만들기로 하였습니다.

→to-do list를 PIP(Picture In Picture) 기능을 써서 구현하여 크롬 브라우저 위에 띄울 수 있게하는 것이 이번 주제의 핵심입니다.
→해당기능이 구현하기 힘들 수도 있기에 다른 주제를 각자 하나씩 생각 해오기로 했습니다.

**Comment by niceaji** [comment]
오늘 회의때 정리하고 새로운 이슈로 만들어주세요
