### ISSUE TITLE
자동 슬라이딩 배너 코드 구현 사이트

### ISSUE THREAD

**Issue by YeSeul-0w0** [CodingDolharrbang/document#4]
[슬라이딩 배너 코드](https://kutar37.tistory.com/entry/%EC%8A%AC%EB%9D%BC%EC%9D%B4%EB%93%9C%EC%87%BC-%EA%B5%AC%ED%98%84-cssjavascriptjquery )
[슬라이딩 배너 코드](https://do-dam.tistory.com/entry/jQuery-%EC%8A%AC%EB%9D%BC%EC%9D%B4%EB%93%9C-%EB%B0%B0%EB%84%88-%EB%A7%8C%EB%93%A4%EA%B8%B0-2%ED%8E%B8 )
[슬라이딩 배너 이외 정지, 상세보기 버튼까지 구현되어 있음](https://webclub.tistory.com/359)

**Comment by niceaji** [comment]
@Choi33 이슈가 끝났으면 close해주시면 됩니다
