### ISSUE TITLE
퀴즈문제

### ISSUE THREAD

**Issue by YeSeul-0w0** [CodingDolharrbang/document#5]
1. 한라산의 해발 높이는 몇 미터일까? 2
1) 1,940m   2) 1,947m   3) 1,980m   4)1,923m

2. 제주말로 '아주 깊다' 라는 의미에서 '만쟁이거머리굴'이라고 불려온 이 굴은 약 10~30만 년 전에 생성된 것으로 추정된다. 총 길이가 약 7.4km에 이르는 다층구조의 용암둥굴의 이름은 무엇일까? 3
1) 김녕사굴   2)미천굴   3)만장굴   4)용천동굴

**Comment by khl2bb** [comment]
제주 사투리 문제도 재밌을것같아요

**Comment by YeSeul-0w0** [comment]
3. 제주 방언 중 '어드레 감디?' 를 표준어로 바꾸면? 1
1) 어디로 가느냐?  2) 어떻게 가니?  3) 어서 오십시오   4)무엇을 하십니까?

방언문제 추가! 
[이쪽에가면방언잘적혀있어!](https://www.jeju.go.kr/culture/dialect/lifeDialect.htm?type=)

**Comment by khl2bb** [comment]
예전에 페이스북에 자기 제주도민 인증 점수는 몇점 해서 퀴즈가 돌아다니곤했는데 못찾겠네요.
링크를 타고 가서 거기서 문제를 풀면 당신의 제주도 사랑 점수는 몇 점 이렇게 나오고
그걸 페이스북 친구들한테 자랑하는 방식이었는데
찾으려니까 안보이네요

찾다가 페이스북에서 사투리 문제같은거 몇 개 발견하기는 했어요.

- 페이스북 사투리 퀴즈 참고
> - https://www.facebook.com/jejufolk/posts/927585270948252/
> - https://www.facebook.com/JEJUJINII/photos/%EC%A0%9C%EC%A3%BC%EB%8F%84%EC%82%AC%ED%88%AC%EB%A6%AC%ED%80%B4%EC%A6%88%EC%A0%95%EB%8B%B5%EC%9D%80-%EB%8C%93%EA%B8%80%EB%A1%9C-%ED%99%95%EC%9D%B8%ED%95%B4%EB%B3%BC%EA%B9%8C%EC%9A%94-%EB%8D%94-%EB%A7%8E%EC%9D%80-%EC%A0%9C%EC%A3%BC%EA%BF%80%ED%8C%81%EC%9D%B4-%EA%B6%81%EA%B8%88%ED%95%98%EB%8B%A4%EB%A9%B4-cilck-httpswwwjejujinikrevte10e027b/1853904488040322/
> - https://www.facebook.com/happyjejudo/photos/%EC%A0%9C%EC%A3%BC-%EB%B0%94%EB%A1%9C%EC%95%8C%EA%B8%B0-%EC%9D%B4%EB%B2%A4%ED%8A%B8-4%EA%B5%90%EC%8B%9C%EC%A0%9C%EC%A3%BC%EC%96%B4%EB%A5%BC-%EC%95%8C%EC%95%84%EB%B3%B4%EA%B8%B0-%EC%9C%84%ED%95%9C-%EB%A7%88%EC%A7%80%EB%A7%89-%ED%80%B4%EC%A6%88%EC%95%84%EB%9E%98-%EB%AC%B8%EC%A0%9C%EB%A5%BC-%EB%B3%B4%EA%B3%A0-%EB%B6%80%EB%B6%84%EC%97%90-%EB%93%A4%EC%96%B4-%EA%B0%88-%EB%8B%A8%EC%96%B4%EB%A5%BC-%EB%8C%93%EA%B8%80%EB%A1%9C-%EB%82%A8%EA%B2%A8%EC%A3%BC%EC%84%B8%EC%9A%94%EF%B8%8F-%EC%9D%91%EB%AA%A8%EA%B8%B0%EA%B0%84-2016%EB%85%84-9/987295718047668/

**Comment by whe0107** [comment]
4. 제주도의 특산물이 아닌 것은? 4
1) 한라봉 2) 은갈치 3) 흑돼지 4) 삼다수

5.  2018년 3월 30일에 정식 개장된 제주 시장은? 1
1) 동문 시장 2) 올레시장 3) 서문시장 4) 보성시장

6. 제주도는 흔히 삼다도라고 한다. 삼다도의 요소에 해당하는 않는 것은? 2
1) 돌 2) 말  3) 여자 4) 바람

7. 제주 사투리 '제기제기'는 무슨 뜻인가? 1
1) 빨리빨리 2) 많이많이 3)조금조금 4) 찔끔찔끔

8. 제주에는 소형 화산체인 오름이 많다. 제주의 오름의 총 갯수는? 3
1) 365개 2) 355개 3) 368개 4) 367개

**Comment by whe0107** [comment]
9. 제주도 제주시에 속하는 바다는? 1
1) 월정리 해변 2) 중문 해변 3) 표선 해변 4) 하모 해변

10. 제주 자연문화재 중 유네스코 세계문화유산에 등재되지않은 것은? 4
1) 만장굴 2) 거문오름 3) 성산 일출봉 4) 주상절리

11.  유네스코는 오랜 세월 이어 온 제주해녀문화의 가치와 보전의 필요성을 인정해 인류무형문화유산으로 등재했다. 등재된 년도는? 2
1) 2017년 2) 21016년 3) 2015년 4) 2014년

12. 제주도의 최남단에 있는 섬은? 1
1) 마라도 2) 비앙도 3) 가파도 4) 우도

13. 2020년에 제주 4.3 사건은 몇 주년이 되었는가? 4
1) 69주년 2) 70주년 3) 71년 4) 72년

14.  제주말로 도체비꽃은 어떤 꽃인가? 2
1) 유채꽃 2) 수국 3) 동백 3) 벚꽃

**Comment by YeSeul-0w0** [comment]
15번 답 4번
16번 답 3번
17번 답 2번 - 위에 올려준 페이스북 방언 링크에서 따온 문제
18번 답 1번
19번 답 4번
20번 답 3번

문제에 대한 상세부분은 json파일로 봐주세요
