### ISSUE TITLE
퀴즈 정답 확인

### ISSUE THREAD

**Issue by YeSeul-0w0** [CodingDolharrbang/document#8]
Jquery를 이용하여 퀴즈 정답 판별

**Comment by niceaji** [comment]
@Choi33 이슈를 https://github.com/CodingDolharrbang/JejuQuiz/issues 이곳에서 만드는게 좋겠네요 :)

**Comment by YeSeul-0w0** [comment]
@niceaji 네! [옮겼습니다!!](https://github.com/CodingDolharrbang/JejuQuiz/issues/7)
